document.addEventListener("DOMContentLoaded",()=>{
// === BLOG RICH TEXT CALLOUTS ===
const richText=document.querySelector('.post-body');if(richText){const map={'H4':'success','H5':'tip','H6':'warning'};Object.entries(map).forEach(([tag,type])=>{const source=document.querySelector(`[fs-richtext-source="${type}"]`);if(!source)return;Array.from(richText.querySelectorAll(tag)).forEach(heading=>{const clone=source.cloneNode(true);clone.removeAttribute('fs-richtext-source');clone.style.display='';const titleEl=clone.querySelector('[fs-richtext-field="title"]');if(titleEl)titleEl.textContent=heading.textContent;const contentEls=[];let sibling=heading.nextElementSibling;while(sibling&&!['H1','H2','H3','H4','H5','H6','HR'].includes(sibling.tagName)){const next=sibling.nextElementSibling;contentEls.push(sibling);sibling=next;}const contentDiv=clone.querySelector('[fs-richtext-field="content"]');if(contentDiv&&contentEls.length){contentDiv.innerHTML='';contentEls.forEach(el=>contentDiv.appendChild(el));}heading.replaceWith(clone);});});document.querySelectorAll('[fs-richtext-source]').forEach(el=>el.remove());}

// === UTM TRACKING ===
const utmKeys=['utm_source','utm_medium','utm_campaign','utm_content','utm_keyword','utm_ad_group','gclid','fbclid'];const sp=new URLSearchParams(window.location.search);let hasNewUtm=false;utmKeys.forEach(k=>{const v=sp.get(k);if(v){sessionStorage.setItem(k,v);hasNewUtm=true;}});if(hasNewUtm)sessionStorage.setItem('utm_landing',window.location.href);

function getUtm(k){return sessionStorage.getItem(k)||'';}
function getReferralSource(){const src=getUtm('utm_source').toLowerCase(),med=getUtm('utm_medium').toLowerCase(),gc=getUtm('gclid');if(gc)return'Google Ads';if(src==='google'&&med==='cpc')return'Google Ads';if((src==='facebook'||src==='instagram')&&med==='paid_social')return'Meta Ads';if(src==='facebook'&&(med==='social'||med==='organic'))return'Facebook';if(src==='instagram'&&(med==='social'||med==='organic'))return'Instagram';if(!src&&!med&&!gc)return'SEO';return src||'SEO';}
function fillUtmFields(form){const fields={utm_source:getUtm('utm_source'),utm_medium:getUtm('utm_medium'),utm_campaign:getUtm('utm_campaign'),utm_content:getUtm('utm_content'),utm_keyword:getUtm('utm_keyword'),utm_ad_group:getUtm('utm_ad_group')};Object.entries(fields).forEach(([name,val])=>{const el=form.querySelector(`input[name="${name}"]`);if(el)el.value=val;});const gc=getUtm('gclid'),fb=getUtm('fbclid');let custom=[];if(gc)custom.push('gclid='+gc);if(fb)custom.push('fbclid='+fb);const ctEl=form.querySelector('input[name="utm_custom_tracking"]');if(ctEl)ctEl.value=custom.join(';');const rsEl=form.querySelector('input[name="referral_source"]');if(rsEl)rsEl.value=getReferralSource();const puEl=form.querySelector('input[name="page_url"]');if(puEl)puEl.value=window.location.href;}

// === DYNAMIC YEAR ===
const yearEl=document.querySelector("[data-year]");if(yearEl){const sy=parseInt(yearEl.getAttribute("data-year"),10);const cy=new Date().getFullYear();if(!isNaN(sy)){yearEl.textContent=cy>sy?`${sy}–${cy}`:`${cy}`}else{yearEl.textContent=cy}}

// === SMART DOTS CLEANUP ===
document.querySelectorAll('.blog-item__dot, .breadcrumbs-dot').forEach(dot=>{const prev=dot.previousElementSibling;const next=dot.nextElementSibling;const isHidden=(el)=>{if(!el)return true;if(el.textContent.trim()==="")return true;return window.getComputedStyle(el).display==='none'};if(isHidden(prev)||isHidden(next))dot.style.display='none';});

// === SWIPER ===
const se=document.querySelector('.testimonials');if(se)new Swiper('.testimonials',{loop:true,slidesPerView:1.1,spaceBetween:12,grabCursor:true,breakpoints:{767:{slidesPerView:3}},navigation:{nextEl:'.btn-next',prevEl:'.btn-prev'},pagination:{el:'.swiper-pagination'}});

// === BUTTON ANIMATIONS ===
const mm=gsap.matchMedia();mm.add("(min-width: 768px)",()=>{document.querySelectorAll('.main-button').forEach(b=>{const o=b.querySelector('.main-button__overlay'),tw=b.querySelector('.main-button__text1'),tb=b.querySelector('.main-button__text2'),ic=b.querySelector('.main-button__icon');if(!o||!tw||!tb)return;gsap.set(o,{yPercent:100,opacity:0});const tl=gsap.timeline({paused:true,defaults:{duration:0.4,ease:"power2.inOut"}});tl.to(b,{color:"black",borderColor:"rgba(16,16,16,0.20)",ease:"none"},0).to(o,{yPercent:0},0).to(tw,{yPercent:-100,opacity:0},0).to(tb,{yPercent:-100},0);if(ic)tl.to(ic,{borderLeftColor:"rgba(16,16,16,0.20)",ease:"none"},0);b.addEventListener('mouseenter',()=>{gsap.to(o,{opacity:1,duration:0.01,overwrite:"auto"});tl.play();});b.addEventListener('mouseleave',()=>{tl.reverse();gsap.to(o,{opacity:0,duration:0.4,ease:"power2.inOut",overwrite:"auto"});});});document.querySelectorAll('.button-secondary').forEach(b=>{const o=b.querySelector('.button-secondary__overlay'),t1=b.querySelector('.button-secondary__text1'),t2=b.querySelector('.button-secondary__text2');if(!o||!t1||!t2)return;gsap.set(o,{yPercent:100,opacity:0});gsap.set(t2,{yPercent:100});const tl=gsap.timeline({paused:true,defaults:{duration:0.4,ease:"power2.inOut"}});tl.to(b,{color:"black",borderColor:"rgba(16,16,16,0.20)",ease:"none"},0).to(o,{yPercent:0},0).to(t1,{yPercent:-100,opacity:0},0).to(t2,{yPercent:-100},0);b.addEventListener('mouseenter',()=>{gsap.to(o,{opacity:1,duration:0.01,overwrite:"auto"});tl.play();});b.addEventListener('mouseleave',()=>{tl.reverse();gsap.to(o,{opacity:0,duration:0.4,ease:"power2.inOut",overwrite:"auto"});});});});

// === FEATURED LOCATIONS ===
window.addEventListener('load',()=>{const tr=document.querySelectorAll('.locations-dd__toggle'),im=document.querySelectorAll('.featured-locations__img'),oc='is-open';if(tr.length>0&&im.length>0){let pi=null;gsap.set(im,{opacity:0,zIndex:1});tr.forEach((t,i)=>{t.addEventListener('click',function(e){if(this.dataset.isClosing==='true')return;const io=this.classList.contains(oc);if(io&&document.querySelectorAll('.'+oc).length===1&&e.isTrusted){e.stopImmediatePropagation();return;}if(!io){tr.forEach((o,ix)=>{if(o!==this&&o.classList.contains(oc)){o.dataset.isClosing='true';o.click();o.classList.remove(oc);setTimeout(()=>delete o.dataset.isClosing,50);pi=ix;}});const ni=im[i],oi=pi!==null?im[pi]:null;if(ni){if(oi&&oi!==ni)gsap.to(oi,{opacity:0,zIndex:2,duration:0.8,ease:"power2.inOut"});gsap.fromTo(ni,{opacity:0,zIndex:10},{opacity:1,duration:0.6,ease:"power2.inOut",overwrite:true});}this.classList.add(oc);pi=i;}else{this.classList.remove(oc);if(im[i])gsap.to(im[i],{opacity:0,zIndex:1,duration:0.6});}},true);});setTimeout(()=>{const ft=tr[0],ce=new MouseEvent('click',{bubbles:true,cancelable:true,view:window});ft.dispatchEvent(ce);if(im[0]){gsap.set(im[0],{opacity:1,zIndex:5});pi=0;}setTimeout(()=>{ScrollTrigger.refresh(true);},500);},400);}});

// === CUSTOM FORM SUBMIT BUTTON ===
document.querySelectorAll('[ms-code-submit-new]').forEach(b=>{b.addEventListener('click',function(e){e.preventDefault();const si=this.getAttribute('ms-code-submit-new');const form=this.closest('form');const os=form?form.querySelector(`[ms-code-submit-old="${si}"]`):document.querySelector(`[ms-code-submit-old="${si}"]`);if(os)os.click();else console.error(`No matching old submit button found for ID: ${si}`);});});

// === NAVBAR & TOUCHBAR ===
const nav=document.querySelector('.navbar'),burger=document.querySelector(".navbar-burger"),touchbar=document.querySelector('.touchbar-mobile'),menuLinks=document.querySelectorAll(".navbar-menu a"),heroSections=['.section-hero'],path=window.location.pathname,isResources=path==='/resources'||path.startsWith('/resources/'),isColored=[].some(x=>path.startsWith(x));if(nav){let tbVis=!1;if(isColored||isResources)nav.classList.add('is-colored');if(touchbar){if(isResources){gsap.set(touchbar,{yPercent:0});tbVis=!0}else gsap.set(touchbar,{yPercent:100})}ScrollTrigger.create({start:'top -1',onEnter:()=>nav.classList.add('is-colored'),onLeaveBack:()=>{if(!isColored&&!isResources)nav.classList.remove('is-colored')}});heroSections.forEach(x=>{const e=document.querySelector(x);if(e)ScrollTrigger.create({trigger:e,start:'bottom top',onEnter:()=>{tbVis=!0;if(touchbar)gsap.to(touchbar,{yPercent:0,duration:.4,ease:'power2.out'})},onLeaveBack:()=>{tbVis=!1;if(touchbar)gsap.to(touchbar,{yPercent:100,duration:.4,ease:'power2.in'})}})});ScrollTrigger.create({trigger:"body",start:"bottom bottom",onEnter:()=>{if(touchbar)gsap.to(touchbar,{yPercent:100,duration:.4,ease:'power2.in'})},onLeaveBack:()=>{if(touchbar&&tbVis)gsap.to(touchbar,{yPercent:0,duration:.4,ease:'power2.out'})}});if(burger)burger.addEventListener("click",()=>{const o=nav.classList.toggle("is-open");document.body.style.overflow=o?'hidden':''});menuLinks.forEach(l=>l.addEventListener("click",()=>{nav.classList.remove("is-open");document.body.style.overflow=''}))}

// === CHOICES.JS WITH AUTO OPTGROUPS ===
let ci=[];document.querySelectorAll('select').forEach(s=>{const isMoveSize=s.name==='move-size';if(isMoveSize){const opts=[...s.querySelectorAll('option')];const frag=document.createDocumentFragment();let currentGroup=null;opts.forEach(o=>{if(o.value.startsWith('group:')){currentGroup=document.createElement('optgroup');currentGroup.label=o.value.replace('group:','');frag.appendChild(currentGroup);}else if(o.value===''||o.disabled){const ph=o.cloneNode(true);ph.selected=true;ph.disabled=true;frag.appendChild(ph);currentGroup=null;}else{const clone=o.cloneNode(true);if(currentGroup)currentGroup.appendChild(clone);else frag.appendChild(clone);}});s.innerHTML='';s.appendChild(frag);}const c=new Choices(s,{searchEnabled:false,itemSelectText:'',shouldSort:false,allowHTML:true});ci.push(c);s.addEventListener('change',function(){$(this).valid();});});

// === DROPDOWN SCROLL HINT ===
ci.forEach(c=>{const wrap=c.containerOuter.element;const ob=new MutationObserver(()=>{if(wrap.classList.contains('is-open')){const dd=wrap.querySelector('.choices__list--dropdown .choices__list');if(dd){setTimeout(()=>{dd.scrollTop=2;setTimeout(()=>{dd.scrollTop=0;},80);},100);}}});ob.observe(wrap,{attributes:true,attributeFilter:['class']});});

// === JQUERY VALIDATION ===
$.validator.addMethod("phoneUS_complete",function(v,e){return this.optional(e)||(e.imask&&e.imask.masked.isComplete);},"Please enter a complete phone number.");$.validator.addMethod("email_strict",function(v,e){return this.optional(e)||/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(v);},"Please enter the correct email address.");$.validator.setDefaults({ignore:"",errorPlacement:function(er,el){er.appendTo(el.closest(".input-wrapper"));},highlight:function(el){const $e=$(el);if($e.is('select')){const inner=$e.closest('.select-wrapper').find('.choices__inner');if(inner.length)inner.addClass('has-error');}else{$e.css("border","1px solid var(--error)").addClass("error-placeholder");}},unhighlight:function(el){const $e=$(el);if($e.is('select')){const inner=$e.closest('.select-wrapper').find('.choices__inner');if(inner.length)inner.removeClass('has-error');}else{$e.css("border","").removeClass("error-placeholder");}}});const mainRules={name:{required:true},phone:{required:true,phoneUS_complete:true},email:{required:true,email_strict:true},'move-size':{required:true},date:{required:true}};const mainMessages={email:{email:"Invalid email"},'move-size':{required:"Please select move size"}};const shortRules={name:{required:true},phone:{required:true,phoneUS_complete:true}};document.querySelectorAll('form[data-name="main-form"]').forEach((f,i)=>{if(i>0)f.removeAttribute('id');const $f=$(f);const fvInst=$f.validate({rules:mainRules,messages:mainMessages});$f.on("submit",function(e){ci.forEach(c=>{$(c.passedElement.element).trigger('change');});if(!fvInst.valid()){e.preventDefault();return false;}fillUtmFields(this);});});document.querySelectorAll('form[data-name="short-form"]').forEach((f,i)=>{if(i>0)f.removeAttribute('id');const $f=$(f);const fvInst=$f.validate({rules:shortRules});$f.on("submit",function(e){if(!fvInst.valid()){e.preventDefault();return false;}fillUtmFields(this);});});

// === PHONE MASK ===
const phoneInputs=document.querySelectorAll('input[name="phone"], input[name="p-phone"]');if(phoneInputs.length>0){const pm={mask:'+1 ({N}00) 000-0000',lazy:false,blocks:{N:{mask:IMask.MaskedRange,from:2,to:9},'0':{mask:IMask.MaskedRange,from:0,to:9}}};phoneInputs.forEach(ie=>{ie.imask=IMask(ie,pm);});}

// === FLATPICKR ===
flatpickr('input[name="date"]',{dateFormat:"d/m/Y",minDate:"today",allowInput:true,disableMobile:true,onReady:function(sd,ds,i){const on=i.input.getAttribute('name');if(i.mobileInput){i.mobileInput.setAttribute('name',on);i.input.removeAttribute('name');}},onChange:function(sd,ds,i){$(i.input).valid();}});

// === ABOUT US TEXT ANIMATION ===
gsap.registerPlugin(ScrollTrigger,SplitText);const as=document.querySelector('.about-us-content');if(as){const at=as.querySelector('h2');if(at){const sp_=new SplitText(at,{type:"words, chars",wordsClass:"split-word"});if(sp_.chars&&sp_.chars.length>0){gsap.fromTo(sp_.chars,{opacity:0.2},{opacity:1,stagger:0.1,ease:"none",scrollTrigger:{trigger:as,start:"top 30%",end:"+=150%",scrub:1,pin:true}});}}}

// === CHARITY SECTION ANIMATION ===
const cs=document.querySelector('.section-charity');if(cs){const initCharity=()=>{gsap.set(".charity-content-w",{width:"100vw",height:"100vh",borderRadius:"0rem"});const tl=gsap.timeline({scrollTrigger:{trigger:cs,start:"top top",end:"+=350%",scrub:1,pin:true,pinSpacing:true,anticipatePin:0,invalidateOnRefresh:true,refreshPriority:-1}});tl.to(".navbar",{yPercent:-100,ease:"power2.inOut",duration:0.2},0);if(touchbar)tl.to(".touchbar-mobile",{yPercent:100,ease:"power2.inOut",duration:0.2},0);tl.fromTo(".charity-content-w",{clipPath:"inset(35vh 35vw round 1rem)"},{clipPath:"inset(0vh 0vw round 0rem)",ease:"none",duration:1},0);tl.fromTo(".charity-content",{yPercent:30,scale:1.05},{yPercent:0,scale:1,ease:"none",duration:1},0);tl.to(".navbar",{yPercent:0,ease:"power2.out",duration:0.2},">");if(touchbar)tl.to(".touchbar-mobile",{yPercent:0,ease:"power2.out",duration:0.2},"<");};if(document.readyState==='complete')setTimeout(initCharity,100);else window.addEventListener('load',()=>{setTimeout(initCharity,100);});}

// === SMOOTH SCROLL TO ANCHOR ===
document.addEventListener('click',function(e){const link=e.target.closest('a[href^="#"]');if(!link)return;const ti=link.getAttribute('href');if(ti==='#')return;const target=document.querySelector(ti);if(!target)return;e.preventDefault();e.stopPropagation();const navHeight=document.querySelector('.navbar')?.offsetHeight||0;const pos=target.getBoundingClientRect().top+window.pageYOffset-navHeight-24;window.scrollTo({top:pos,behavior:'smooth'});if(history.pushState)history.pushState(null,null,ti);},!0);

// === FORM RESET BUTTON ===
document.querySelector('#form-reset')?.addEventListener('click',function(){const f=document.querySelector('#main-form'),d=f?.closest('.w-form')?.querySelector('.w-form-done'),fl=f?.closest('.w-form')?.querySelector('.w-form-fail');if(d)d.style.display='none';if(fl)fl.style.display='none';if(f){f.style.display='block';f.reset();ci.forEach(c=>c.setChoiceByValue(''));}});

// === TABLE OF CONTENTS ===
const tocList=document.querySelector('.table-of-contents__list');if(tocList){document.querySelectorAll('.post-body h2').forEach((h,i)=>{const id='toc-'+(i+1);h.setAttribute('id',id);let text=h.textContent.trim();if(text.indexOf('. ')>-1)text=text.split('. ').slice(1).join('. ');const li=document.createElement('li');li.className='table-of-contents__item';li.innerHTML='<a href="#'+id+'" class="table-of-contents__link">'+text+'</a>';tocList.appendChild(li)});}});

// === SHARE BUTTONS ===
const shareUrl=encodeURIComponent(window.location.href);const shareTitle=encodeURIComponent(document.title);document.querySelectorAll('[data-share]').forEach(btn=>{btn.addEventListener('click',function(e){e.preventDefault();const type=this.getAttribute('data-share');let url='';switch(type){case'facebook':url=`https://www.facebook.com/sharer/sharer.php?u=${shareUrl}`;break;case'linkedin':url=`https://www.linkedin.com/sharing/share-offsite/?url=${shareUrl}`;break;case'x':url=`https://x.com/intent/tweet?url=${shareUrl}&text=${shareTitle}`;break;case'copy':navigator.clipboard.writeText(window.location.href).then(()=>{const origHTML=this.innerHTML;this.innerHTML='<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 10.5L8 14.5L16 6.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';setTimeout(()=>{this.innerHTML=origHTML;},2000);});return;}if(url)window.open(url,'_blank','width=600,height=400');});});

// === EXIT POPUP ===
const exitPopup=document.querySelector('.exit-popup-w');if(exitPopup&&!sessionStorage.getItem('exit_popup_shown')){const exitForm=exitPopup.querySelector('.exit-popup-form');const exitClose=exitPopup.querySelector('.exit-popup-close');const exitOverlay=exitPopup.querySelector('.exit-popup-close-overlay');gsap.set(exitPopup,{autoAlpha:0,display:'none'});gsap.set(exitForm,{xPercent:110});const showPopup=()=>{if(sessionStorage.getItem('exit_popup_shown'))return;sessionStorage.setItem('exit_popup_shown','1');gsap.set(exitPopup,{display:'flex'});gsap.to(exitPopup,{autoAlpha:1,duration:0.3,ease:'power2.out'});gsap.to(exitForm,{xPercent:0,duration:0.5,ease:'power3.out',delay:0.1});};const hidePopup=()=>{gsap.to(exitForm,{xPercent:110,duration:0.4,ease:'power3.in'});gsap.to(exitPopup,{autoAlpha:0,duration:0.3,delay:0.2,ease:'power2.in',onComplete:()=>{gsap.set(exitPopup,{display:'none'});}});};const isMobile=window.matchMedia('(max-width:767px)').matches;if(isMobile){setTimeout(showPopup,20000);}else{document.addEventListener('mouseout',function(e){if(!e.relatedTarget&&e.clientY<5)showPopup();});}if(exitClose)exitClose.addEventListener('click',hidePopup);if(exitOverlay)exitOverlay.addEventListener('click',hidePopup);document.addEventListener('keydown',function(e){if(e.key==='Escape'&&exitPopup.style.display==='flex')hidePopup();});}

// === PAGE TRANSITIONS ===
(function(){const d=300;document.documentElement.style.cssText='opacity:1;transition:opacity '+d+'ms ease';document.addEventListener('click',function(e){const a=e.target.closest('a');if(!a)return;const h=a.getAttribute('href');if(!h||h==='#'||h.startsWith('#')||a.target==='_blank'||h.startsWith('mailto:')||h.startsWith('tel:')||a.hostname!==location.hostname||a.hasAttribute('ms-code-submit-new'))return;e.preventDefault();document.documentElement.style.opacity='0';setTimeout(()=>{window.location=a.href;},d);});window.addEventListener('pageshow',function(){document.documentElement.style.opacity='1';});let last='';function prefetch(e){const a=e.target.closest('a');if(!a)return;const h=a.getAttribute('href');if(!h||h==='#'||h.startsWith('#')||a.target==='_blank'||h.startsWith('mailto:')||h.startsWith('tel:')||a.hostname!==location.hostname||a.href===last)return;last=a.href;const l=document.createElement('link');l.rel='prefetch';l.href=a.href;document.head.appendChild(l);}document.addEventListener('mouseover',prefetch);document.addEventListener('touchstart',prefetch,{passive:true});})();
